<?php
require_once __DIR__.'/../ajax/borrower.php'; require_once __DIR__.'/payment_records.php';
function borrower_loans($id){return lender_rows("SELECT a.*,c.released_at,c.signed_pdf IS NOT NULL has_signed,c.purpose,COALESCE((SELECT SUM(amount_paid) FROM loan_installments WHERE agreement_id=a.agreement_id),0) paid,(SELECT MAX(due_date) FROM loan_installments WHERE agreement_id=a.agreement_id) last_due,EXISTS(SELECT 1 FROM loan_installments WHERE agreement_id=a.agreement_id AND amount_due>amount_paid AND due_date<CURDATE()) overdue FROM loan_agreements a LEFT JOIN lender_contracts c ON c.agreement_id=a.agreement_id WHERE a.borrower_id=? ORDER BY a.agreement_id DESC",[$id]);}
function borrower_dues($id){return lender_rows("SELECT i.*,i.amount_due-i.amount_paid balance FROM loan_installments i JOIN loan_agreements a ON a.agreement_id=i.agreement_id WHERE a.borrower_id=? AND a.status='active' AND i.amount_due>i.amount_paid ORDER BY i.due_date,i.installment_id",[$id]);}
function borrower_history($id){return lender_rows("SELECT p.*,COALESCE(o.method,'Recorded by lender') method,'Paid' payment_status FROM loan_payments p JOIN loan_agreements a ON a.agreement_id=p.agreement_id LEFT JOIN paymongo_orders o ON o.payment_id=p.payment_id WHERE a.borrower_id=? ORDER BY p.payment_date DESC,p.payment_id DESC",[$id]);}
function borrower_can_request($id){return !db("SELECT a.agreement_id FROM loan_agreements a WHERE a.borrower_id=? AND (a.status IN ('draft','active') OR EXISTS(SELECT 1 FROM loan_installments i WHERE i.agreement_id=a.agreement_id AND i.amount_due>i.amount_paid)) LIMIT 1",[$id])->get_result()->num_rows && !db("SELECT request_id FROM borrower_loan_requests WHERE borrower_id=? AND status='pending'",[$id])->get_result()->num_rows;}
function due_label($date){$n=(int)(new DateTimeImmutable('today'))->diff(new DateTimeImmutable($date))->format('%r%a');return $n<0?abs($n).' days overdue':($n===0?'Due today':$n.' days left');}
function due_status($date){return $date<date('Y-m-d')?'Overdue':($date<=date('Y-m-d',strtotime('+7 days'))?'Due soon':'Upcoming');}
function loan_status($a){return $a['status']==='draft'?'Awaiting release':($a['status']==='active'&&$a['overdue']?'Overdue':ucfirst($a['status']));}
function borrower_notices($id){$read=array_column(lender_rows('SELECT event_key FROM borrower_notification_reads WHERE borrower_id=?',[$id]),'event_key');$items=[];foreach(borrower_dues($id) as $i){if($i['due_date']>date('Y-m-d',strtotime('+7 days')))continue;$key=$i['installment_id'].'-'.$i['due_date'].'-'.($i['due_date']<date('Y-m-d')?'overdue':'reminder');if(in_array($key,$read,true))continue;$items[]=['key'=>$key,'text'=>due_status($i['due_date']).': '.money($i['balance']).' for DUE-'.$i['installment_id'].' on '.$i['due_date'].'. '.due_label($i['due_date']).'.'];}return $items;}
function portal_start($title,$active){global $borrowerAccount;$u=$borrowerAccount;
?><!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= e($title) ?> | Utang Wise</title><link rel="stylesheet" href="../assets/css/client-dashboard.css"><link rel="stylesheet" href="../assets/css/borrower-flow.css"><link rel="stylesheet" href="../assets/css/borrower-portal.css"></head><body><div class="dashboard-layout"><aside class="sidebar" id="sidebar"><div class="brand"><img width="46" src="../assets/logo/utangwiselogo.png" alt="Utang Wise"><div><h2>UTANG WISE</h2><small>LENDING MADE SIMPLE</small></div></div><nav class="sidebar-menu"><?php foreach(['client-dashboard'=>'Dashboard','profile'=>'Profile','my-loans'=>'My Loans','request-loan'=>'Request Loan','payments'=>'Payments','payment-extension'=>'Payment Extension','payment-history'=>'Payment History','signed-agreement'=>'Agreements'] as $route=>$label): ?><a class="menu-item <?= $route===$active?'active':'' ?>" href="<?= e($route) ?>.php"><?= e($label) ?></a><?php endforeach; ?></nav><?php borrower_logout_button(); ?></aside><main class="main-area"><header class="topbar"><button type="button" id="portalMenu" aria-label="Toggle menu">Menu</button><strong><?= e($u['user_fn'].' '.$u['user_ln']) ?></strong><details class="portal-notifications"><summary>Notifications (<?= count($items=borrower_notices($u['user_id'])) ?>)</summary><div><?php if(!$items): ?><p>No unread reminders.</p><?php endif; foreach($items as $item): ?><form method="post" action="../controllers/borrower-notifications.php"><?php csrf(); ?><input type="hidden" name="event_key" value="<?= e($item['key']) ?>"><p><?= e($item['text']) ?></p><button>Mark as read</button></form><?php endforeach; ?><a href="payments.php">View payments</a></div></details></header><div class="dashboard-body"><section class="dashboard-content"><div class="welcome-section"><h1><?= e($title) ?></h1></div><?php notice();}
function portal_end(){?></section></div></main></div><script src="../assets/js/borrower-portal.js" defer></script><?php uw_success_assets(); ?></body></html><?php }
function portal_history_table($rows){?><div class="table-wrapper"><table><thead><tr><th>Payment ID</th><th>Date</th><th>Amount</th><th>Method</th><th>Status</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td>PAY-<?= (int)$r['payment_id'] ?></td><td><?= e($r['payment_date']) ?></td><td><?= money($r['amount']) ?></td><td><?= e($r['method']) ?></td><td><?= e($r['payment_status']) ?></td></tr><?php endforeach; if(!$rows): ?><tr><td colspan="5">No payments recorded yet.</td></tr><?php endif; ?></tbody></table></div><?php }
