<div class="page-heading"><div><h1><?= e($title) ?></h1><p><?= e($description) ?></p></div></div>
<div id="lenderNotice" class="uw-notice" role="status" hidden></div>
<section class="summary-grid"><?php $color=0; foreach($counts as $label=>$count): ?><div class="summary-card"><div class="summary-icon <?= ['blue','orange','green','red'][$color++%4] ?>"><span class="uw-summary-symbol"><?= ['#','…','✓','×'][($color-1)%4] ?></span></div><div><span class="summary-label"><?= e($label) ?></span><strong><?= (int)$count ?></strong></div></div><?php endforeach; ?></section>
<?php if($mode==='loaners'): ?><p class="uw-caption">Total loaners counts approved accounts. Active includes overdue loans. Date Registered shows the application submission date where available.</p><?php endif; ?>
<section class="uw-table-card applications-table-card">
<div class="uw-filters"><label>Search<input id="lenderSearch" type="search" placeholder="Search names, IDs or details"></label><label>Status<select id="lenderStatus"><option value="">All statuses</option><?php foreach(array_unique(array_column($tableRows,'status')) as $status): ?><option><?= e($status) ?></option><?php endforeach; ?></select></label>
<label>Loan type<select id="lenderType"><option value="">All loan types</option><option>Money</option><option>Item</option><option>No loan</option></select></label><label>Installments<select id="lenderTerm"><option value="">All terms</option><option value="3">3 months</option><option value="6">6 months</option><option value="12">12 months</option></select></label><button type="button" class="uw-button secondary" id="lenderReset">Reset</button></div>
<div class="uw-table-scroll table-wrapper"><table id="lenderTable"><thead><tr><?php foreach($headers as $header): ?><th><?= e($header) ?></th><?php endforeach; ?></tr></thead><tbody><?php foreach($tableRows as $row): ?><tr data-status="<?= e($row['status']) ?>" data-type="<?= e($row['type']==='Installment'?'Money':$row['type']) ?>" data-term="<?= e($row['term']) ?>"><?php foreach($row['cells'] as $cell): ?><td><?= e($cell) ?></td><?php endforeach; ?><td><button type="button" class="uw-button secondary" data-view="<?= e($row['kind']) ?>" data-id="<?= (int)$row['id'] ?>"><?= e($row['button']) ?></button></td></tr><?php endforeach; ?></tbody></table></div>
</section>
<dialog id="lenderDialog" aria-labelledby="dialogTitle"><header class="uw-dialog-header"><h2 id="dialogTitle">Application details</h2><button type="button" class="uw-button secondary" id="closeLenderDialog" aria-label="Close dialog">Close</button></header><div id="dialogContent"></div></dialog>
<script type="application/json" id="lenderConfig"><?= json_encode(['csrf'=>$_SESSION['csrf'],'today'=>date('Y-m-d'),'mode'=>$mode],JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) ?></script>
