<?php require __DIR__.'/../helpers/lending.php';$lenderAccount=lender_user(); ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Settings | Utang Wise</title><link rel="stylesheet" href="../assets/css/integ-lender/lender-live.css"><link rel="stylesheet" href="../assets/css/borrower-portal.css"><?php uw_role_design_assets('lender','dashboard'); ?></head><body><div class="admin-layout"><?php require __DIR__.'/../helpers/lender_sidebar.php'; ?><main class="main-content"><?php require __DIR__.'/../helpers/lender_topbar.php'; ?><div class="live-body"><h1>Account settings</h1><?php notice(); ?>
<section class="dashboard-card"><h2>Profile and sign-in details</h2><form class="portal-form" method="post" action="../controllers/lender-settings.php"><?php csrf(); ?>
<label>First name<input name="user_fn" maxlength="255" value="<?= e($lenderAccount['user_fn']) ?>" required autocomplete="given-name"></label>
<label>Last name<input name="user_ln" maxlength="255" value="<?= e($lenderAccount['user_ln']) ?>" required autocomplete="family-name"></label>
<label>Email<input type="email" name="email" maxlength="255" value="<?= e($lenderAccount['email']) ?>" required autocomplete="email"></label>
<label>Mobile number (+63)<input name="phone" inputmode="numeric" pattern="9[0-9]{9}" maxlength="10" value="<?= e(preg_replace('/^(?:\+63|0)/','',$lenderAccount['phone'])) ?>" required autocomplete="tel-national"></label>
<label>Current password<input type="password" name="current_password" required autocomplete="current-password"></label>
<label>New password (optional)<input type="password" name="new_password" minlength="8" maxlength="72" autocomplete="new-password"></label>
<label>Confirm new password<input type="password" name="confirm_new_password" autocomplete="new-password"></label><p>Leave both new-password fields empty to keep your current password. Existing signed agreements retain their original details.</p><button>Save account settings</button></form></section>
<section class="dashboard-card"><h2>Profile picture</h2><p>Update the photo shown on your approved public lender profile.</p><a class="portal-button" href="profile-photo.php">Manage profile photo</a></section></div></main></div><script src="../assets/js/lender-notifications.js" defer></script><?php uw_success_assets(); ?></body></html>
